version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/react-arrow

    steps:
      - checkout
      - run: yarn
      - run: yarn run build
      - run: npm install -g bundlecop
      - run: bundlecop submit dist/


